version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=twitter_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Dim4s3388***
    networks:
      - twitter_network

  web:
    build: .
    command: >
      sh -c "sleep 10 &&
      python manage.py migrate &&
      gunicorn --workers 3 --bind 0.0.0.0:8000 --timeout 120 twitter_corujinha.wsgi:application"
    volumes:
      - .:/app
      - ./static:/app/staticfiles
      - ./media:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=dj4%84jf^@khj&fsdf7!flkdfs0sdSAD!$%j3
      - DJANGO_DEBUG=True
      - POSTGRES_DB=twitter_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Dim4s3388***
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    networks:
      - twitter_network

  frontend:
    build: ../projetoFinal_front
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_API_URL=http://localhost:8000
    depends_on:
      - web
    networks:
      - twitter_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - web
      - frontend
    networks:
      - twitter_network

networks:
  twitter_network:
    driver: bridge

volumes:
  postgres_data:
