version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: twitter_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: twitterclone123
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - twitter_network

  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn --workers 3 --bind 0.0.0.0:8000 twitter_corujinha.wsgi:application"
    volumes:
      - ./:/app
      - ./static:/app/staticfiles
      - ./media:/app/media
    environment:
      DJANGO_SECRET_KEY: dj4%84jf^@khj&fsdf7!flkdfs0sdSAD!$%j3
      DJANGO_DEBUG: 'True'
      POSTGRES_DB: twitter_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dim4s3388***
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    networks:
      - twitter_network
    depends_on:
      - db

  frontend:
    build: ../projetoFinal_front
    environment:
      VUE_APP_API_URL: http://localhost:8000/api/
    ports:
      - "8080:80"
    networks:
      - twitter_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - web
      - frontend
    command: sh -c "nginx -g 'daemon off;'"
    networks:
      - twitter_network

volumes:
  pg_data:

networks:
  twitter_network:
    driver: bridge
