# Generated by Django 5.1.1 on 2024-10-03 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="follow",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="like",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="tweet",
            options={"verbose_name": "Tweet", "verbose_name_plural": "Tweets"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="tweet",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="core.tweet",
                verbose_name="Tweet Original",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_images/",
                verbose_name="Imagem de Perfil",
            ),
        ),
        migrations.AddIndex(
            model_name="tweet",
            index=models.Index(
                fields=["author", "created_at"], name="core_tweet_author__948611_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tweet",
            index=models.Index(fields=["parent"], name="core_tweet_parent__85c91f_idx"),
        ),
    ]
