# Generated by Django 5.1.1 on 2024-10-17 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_user_birth_date_remove_user_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Comentário",
                "verbose_name_plural": "Comentários",
            },
        ),
        migrations.AlterModelOptions(
            name="follow",
            options={"verbose_name": "Seguir", "verbose_name_plural": "Seguidores"},
        ),
        migrations.AddField(
            model_name="tweet",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_tweets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Curtidas",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="tweet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_by",
                to="core.tweet",
                verbose_name="Tweet",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["follower", "followed"], name="core_follow_followe_db4ef4_idx"
            ),
        ),
    ]
